training-bot/labs11-trainingBot-FE

- client/src/App.js
- client/src/Auth/Auth.js
- client/src/Auth/auth-variables.js
- client/src/components/LandingPage/LandingPageView.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/history.js
Added second button 'login' that will now redirect you to auth0 authentication service.
Upon successfully signing in, you'll be redirected to /training-series
- Added Auth folder at root.
- Added history.js at root.
- app.js changed to pass handleAuthenticate() to training-series.
> Authentication with Auth0

- client/src/App.js
- client/src/Auth/auth0-variables.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Add training series view, list, and card components

- README.md
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Navigation/Navigation.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMembersList.js
- client/src/components/TeamMembers/TeamMembersView.js
- node_modules/.yarn-integrity
- package.json
I added the structure for dynamically rendering team member cards with a map. On my local host it renders one card with some incomplete information. I left a comment to put in the endpoint for getting team members by user id once it's finished. 
The current endpoint is set to grab all users, but dynamically rendering users is incomplete.
> Add team member card component

- client/package.json
- client/src/App.js
- client/src/Auth/Auth.js
- client/src/Auth/auth0-variables.js
- client/src/Callback/callback.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Profile/profile.js
- client/src/routes.js
- client/yarn.lock
Authentication File reworked and easier to work with. 
The token & userprofile will be set to localstorage now.
Upon refresh, user stays logged in. (Token exp. not implemented currently)
> Authentication rework and Cleanup

- client/src/components/Dashboard/Dashboard.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
- client/src/store/actions/trainingSeriesActions.js
- client/src/store/reducers/trainingSeriesReducer.js
Implemented training series Delete functionality
> Training series delete

- client/src/components/AppBar/AppBar.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Profile/ProfileView.js
Minor appbar update and removed profile redirect on dashboard
> Appbar update

- client/src/components/Modals/TrainingSeriesModal.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/store/actions/trainingSeriesActions.js
- client/src/store/reducers/trainingSeriesReducer.js
- node_modules/.yarn-integrity
Functionality to Edit training series implemented. A modal will pop-up with the pre-filled data depending on which card you clicked 'edit' on. 
The UI will update upon finished edit.
Checked if adding training series still works.
Checked if editing works.
Checked if form repopulates upon editing. 
Checked if UI updates upon submit.
> Brandon series edit

- client/src/components/Modals/PostModal.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/store/actions/postsActions.js
- client/src/store/reducers/postsReducer.js
- TrainingSeriesPosts gets series/post information in componentDidMount to prevent crashing if loading specific page before mounting parent components
- Create PostModal form to create new post, successfully add to db
- TrainingSeriesPosts refetches training series posts after adding a post
> Get trainingseries+posts, POST a new post, have component automatically update with new posts

- client/src/App.js
- client/src/components/AppBar/AppBar.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Progress/ProgressCircle.js
- client/src/routes.js
Refactored where app bar is being rendered so it doesn't reload when switching routes. Added progress circle when dashboard is loading.
> Appbar and Dashboard refactor

- client/src/components/Callback/callback.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Modals/TeamMemberModal.js
- client/src/components/Profile/ProfileView.js
- client/src/components/Progress/ProgressCircle.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/store/actions/userActions.js
- client/src/store/reducers/index.js
- client/src/store/reducers/userReducer.js
This implementation refactored the Dashboard and Profile to utilize the redux store. 
Also added our icon to the progress bar :)
All services appear functional based on my testing.
> User redux

- client/src/components/AppBar/AppBar.js
- client/src/routes.js
Navbar now only shows on routes with /home
> Added navbar to /home routes

- client/src/components/AppBar/AppBar.js
- client/src/routes.js
Reverts training-bot/labs11-trainingBot-FE#48
> Revert "Added navbar to /home routes"

- client/src/components/Modals/PostModal.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/store/actions/postsActions.js
- client/src/store/reducers/postsReducer.js
- Clear post object state when user clicks "Cancel" on Create a Post/Edit Post modal
- Successful DELETE of training series post and update of state
> Delete posts/clear state

- client/src/components/Modals/TeamMemberModal.js
Fixed bug that would clear the modal form when the edit button is selected on a team member twice.
> Fixed bug that would clear the modal form when the edit button is selected on a team member twice and crash when saving an edit. 

- client/src/App.js
- client/src/components/AppBar/AppBar.js
- client/src/components/LandingPage/LandingPageView.js
- client/src/components/Profile/ProfileView.js
- client/src/index.css
- client/src/index.js
- client/src/store/actions/index.js
Implemented Landing Page styling.
Implemented Navigation Bar. Navbar conditionally renders on the Landing page - So it can display different information just for the Landing Page.
Navbar is mobile friendly.
> Navigation & Landing Page

- client/src/components/Stripe/CheckoutForm.js
- client/src/components/Stripe/StripeView.js
- client/src/store/actions/index.js
- client/src/store/actions/stripeActions.js
- client/src/store/reducers/index.js
- client/src/store/reducers/stripeReducer.js
- client/src/store/reducers/userReducer.js
Updates interface for stripe and includes redux
Tested locally. Does require the stripe-redux BE branch to test
> Stripe redux

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/PostModal.js
- client/src/components/Modals/PostOptionsModal.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/Profile/ProfileView.js
- client/src/components/Progress/ProgressCircle.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
Adds manage posts to the ... modal. Cleans up profile page. Starts to organize the dashboard
Tested locally
> Manage training series post.

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
Add dashboard components and adjust styling
Tested locally
> Dashboard update and responsiveness

- client/package.json
- client/src/components/Modals/addTeamMemberToTrainingSeriesModal.js
- client/src/components/Modals/addToTrainingSeriesModal.js
- client/src/components/Modals/deleteModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/store/actions/teamMembersActions.js
- client/src/store/reducers/teamMembersReducer.js
Added the functionality to add/remove a team member to/from a training series inside of a team member's page. 
When adding a training series to a team member, the list of available training series will filter out those that have already been assigned. 
> Team member can be added and deleted from a training series from the team member page

- client/src/components/Modals/SlideDownModal.js
- client/src/components/Modals/TeamMemberModal.js
- client/src/components/Modals/TrainingSeriesModal.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMemberMenuBtn.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
Updates the dashboard UX and styling
Tested locally
> Dashboard ux

- client/package.json
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Dashboard/DashboardView.js
- client/src/components/TeamMembers/TeamMembersList.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
- client/yarn.lock
User can paginate through team members and training series independently. Can also set how many to view of each
Tested locally
> Pagination

- client/src/components/Dashboard/DashboardView.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
Added media query to make the dashboard responsive
> Responsive dashboard

- client/src/components/Modals/PostModal.js
- client/src/components/Modals/addTeamMemberToTrainingSeriesModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
Responsive design for:
- TeamMemberPage
- AddTeamMemberToTrainingSeriesModal
- TrainingSeriesPosts
- PostModal
> Responsiveness for TrainingSeriesPosts, TeamMemberPage, and accompanying modals

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/addTeamMemberToTrainingSeriesModal.js
- client/src/components/Notifications/Notification.js
- client/src/components/Notifications/NotificationsList.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TeamMembers/TeamMemberMenuBtn.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
- client/src/store/actions/index.js
- client/src/store/actions/notificationsActions.js
- client/src/store/reducers/index.js
- client/src/store/reducers/notificationsReducer.js
Add notification dashboard with pagination and filtering by email, text, or all. 
Tested locally running local server with notification helper function changes. 
Start both back end PR and front end PR to test locally.
> Notifications Dashboard

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/Modals/TeamMemberOptions.js
- client/src/components/TeamMembers/TeamMemberMenuBtn.js
- client/src/components/TrainingSeries/CreateTrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/store/reducers/trainingSeriesReducer.js
Added new flow for adding a training series. Removed modal, added component, and added loading state with a route to managing messages on the newly created training series. Also changed working on dropdown modals from "edit" to "manage"
Tested locally with development server.
> Training series route restructure

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/TrainingSeriesModal.js
- client/src/components/Navigation/ReturnToDashboard.js
- client/src/components/TrainingSeries/CreateTrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
- client/src/store/reducers/teamMembersReducer.js
- client/src/store/reducers/trainingSeriesReducer.js
Updated dashboard team member and training series list orders. Recently added show up as first on list for better user experience.
Tested on local host with development server.
> Update dashboard list orders

- client/src/components/TrainingSeries/TrainingSeriesAssignment.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/store/actions/trainingSeriesActions.js
- client/src/store/reducers/postsReducer.js
- client/src/store/reducers/trainingSeriesReducer.js
- Refactor training series page to include assigned team members and add ability to live update the training series' title
> Friedel series refactor

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMemberSnackbar.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- Refactored adding members to a training series into a new page. 
- Calendar only allows for selection of current day and forward.
- If no team members are present, User will be presented with a text letting them know.
- Snackbar will show on training series main view upon completion of assigning members.
- User cannot submit unless at least one member is chosen.
Tested by developer 😃
https://trello.com/c/3lE5QScz
> Trainingseries refactor

- client/package.json
- client/src/components/TeamMembers/TeamMembersList.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- Added search functionality for team members and training series on the dashboard using fuse.js.
- Team members can be searched by first name, last name, and job description. 
- Training series are searched by title. 
- Pagination lengths adjust according to the size of the searched list.
> Added search functionality on the dashboard for team members and training series

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/Modals/TeamMemberOptions.js
- client/src/components/Modals/TrainingSeriesModal.js
- client/src/components/Modals/addTeamMemberToTrainingSeriesModal.js
- client/src/components/Modals/deleteModal.js
- client/src/components/Profile/ProfileView.js
- client/src/components/Stripe/CheckoutForm.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- client/src/components/TeamMembers/TeamMembersList.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMemberSnackbar.js
- client/src/components/TrainingSeries/CreatePost.js
- client/src/components/TrainingSeries/PostPage.js
- client/src/components/TrainingSeries/SnackBarTrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesAssignment.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
Add delete modal to all components that have delete option. Remove unused components.
Locally tested on development server
> Delete modal updates and additions

- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
When assigning multiple users to a training series, the users will be filtered based on if they are currently assigned to the training series.
I added new team members to see if they would show up when assigned -- works
I removed a user from a training series and checked if they show up -- works
TRELLO:https://trello.com/c/8bLsSfRB
> Filter assigned

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
bottom border on team members list
search button drops down search
wider columns
Tested locally
> Dashboard tweaks

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/SlideDownModal.js
- client/src/components/Modals/TeamMemberOptions.js
- client/src/components/Modals/deleteModal.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMembersList.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
When deleting training series or team members, message dashboard now updates in real time with accurate data.
Tested locally with development server.
> Fix notification live update issues

- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- Added search functionality on the training series page. A user can search the messages on a training series. 
> Added search functionality to search posts on the training series page.

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/addTeamMemberToTrainingSeriesModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- Disable button to assign member to series from team member page if user hasn't created any training series
- Provide link to create training series
- Fix bug on training series page that displayed "no team members" text upon hard refresh
- Implement bug prevention on team member page
> Disable button to assign member to series from team member page

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Snackbar/Snackbar.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/CreateTrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/store/reducers/userReducer.js
- client/yarn.lock
- Implemented required on all forms.
- Creating a new team member will now submit on the form instead of onClick. 
- When routed to the newly created team member, a snackbar will appear letting the user know the process was successful.
- Loading GIF on submit button while pushing to newly created team member.
- Forms now are required to submit
- Possible fix of error where adding a team member would crash the site.
- Usage test
> Validate forms

- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/CreatePost.js
- client/src/components/TrainingSeries/CreateTrainingSeries.js
...to the bottom of the page. Added a cancel button to the create training series page. Wired the cancel 
- Repositioned buttons on the team member and create post pages to the bottom of the page.
- Added cancel button the create training series page that routes back to the dashboard
- Cancel button on add team member page routes back to the dashboard.
> Repositioned and refactored buttons 

- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
Adjusted button location on training series posts
Hides search on training series post
Added paper to add member page
Tested locally
> Training series button adjustments

- client/src/components/Dashboard/DashboardView.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AssignMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- Refactored addtraningseries modal into separate page
> Refactor assignment into new page

- client/src/components/Callback/callback.js
- client/src/components/Dashboard/DashboardView.js
- client/src/store/reducers/userReducer.js
Quick fix to resolve issue with user logging in for the first time crashing app.
> Fixed bug on first login crashing app

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Notifications/Notification.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
Can see assigned members from the dashboard now
height of dashboard items are better
Tested locally
> Added number of assigned users to training series

- client/src/components/TeamMembers/TeamMemberPageContainer/AssignMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- Improve UX for the flow of assigning a single member to a training series
- Disable past dates in date picker
- Style component
- Route back to dashboard upon completion
**Note: Snackbar confirming successful assignment is still needed
> UX improvements and complete functionality of team member assignment

- client/src/components/Dashboard/DashboardView.js
- Add code back into DashboardView that was accidentally removed (additional route for training series assignment view)
> Bug fix: Blank assignment page

- client/src/components/Profile/ProfileView.js
- client/src/components/Progress/ProgressCircle.js
- client/src/components/Stripe/CheckoutForm.js
- client/src/components/Stripe/unsubscribeModal.js
- client/src/store/reducers/userReducer.js
Makes profile page fully responsive. Adds pricing to the profile page with integrated subscription buttons.
- [x ] New feature (non-breaking change which adds functionality)
Locally
> Profile pricing

- client/src/components/Dashboard/DashboardView.js
- client/src/components/Modals/deleteModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AssignMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- client/src/components/TeamMembers/TeamMembersView.js
- UX flow complete for Team Member page and Create A New Team Member
- Changed routes to return to dashboard
- Add snackbar to Dashboard after a new member is created
> Team Member/Add Team Member UX flow complete

- client/src/components/Dashboard/DashboardView.js
- Bug fix: change conditionals to prevent success snackbar from appearing at random times (the one that shows up after a team member is successfully assigned to a training series)
- **Note** I also merged development into this branch, which is why there are so many commits on this.
> Bug fix: Random snackbar

- client/src/components/TeamMembers/TeamMemberPageContainer/AssignMemberPage.js
- client/src/store/reducers/postsReducer.js
Bandaid bug fix to ensure Dashboard live updates notifications. (using setTimeout)
Bug fix: Fix temporary duplicate message after initially creating it.
> Bug fix: Live update of notifications table from team member page

- client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPageView.js
- client/yarn.lock
> Changed naming for several snackbars

- client/src/components/Modals/deleteModal.js
- client/src/components/Notifications/NotificationsList.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/TrainingSeries/TrainingSeriesList.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/components/TrainingSeries/TrainingSeriesView.js
- Messaging updates on empty paper components for better UX messaging
- Added min height/max height to Dashboard papers depending on media query
- Styled delete modal
> UX messaging and styling updates to Dashboard, Training Series page

- client/src/components/Modals/deleteModal.js
- client/src/components/Profile/ProfileView.js
- client/src/components/Stripe/CheckoutForm.js
- client/src/components/Stripe/unsubscribeModal.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
* Add placeholder text on training series message page
* Add placeholder text styling on team member page to match the others
* Style unsubscribe modal to match others
* Style account deletion modal to math others
* Style active subscription modal to match others (when trying to delete your account with active sub)
* Update profile payment form spacing and button style
> Alex minor styling / consistency fixes

- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- Display one delete icon per training series assignment on team member's page (was only displaying one icon per list)
- Styling is fully responsive
> Bug fix: Display one delete icon per series on team member page; styling

- client/src/components/authenticate/authenticate.js
- client/src/routes.js
- Reworked the Auth HOC to include axios defaults on sending backend requests. All api calls now send an Authorization header with the token provided.
- I walked through the entire app and couldn't find any breaking changes.
> HOC implemented to authenticate routes

- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
- Scratch previous updates and style layout with multiple columns of checkboxes
> Assign multiple members page styling updates

- client/package.json
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/yarn.lock
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Tested locally
> Add team member form validation

- client/src/components/Modals/TeamMemberOptions.js
- client/src/components/TeamMembers/TeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AssignMemberPage.js
- client/src/components/TrainingSeries/TrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
Added ability to click on team member and training series list items on the dashboard and on the training series post page. 
Added bouncing bot after a user clicks save on the assign button of the team member assign page.
> Added list item click through and bouncing bot. 

- client/src/components/AppBar/AppBar.js
- client/src/components/Dashboard/DashboardView.js
- client/src/components/Navigation/ReturnToDashboard.js
- client/src/components/Notifications/NotificationsView.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMember.js
- client/src/components/TrainingSeries/AddMembersToTrainingSeries/AddMembersView.js
- client/src/components/TrainingSeries/CreatePost.js
- client/src/components/TrainingSeries/CreateTrainingSeries.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/index.css
- Fix Training Series title bug where form was submitting even though input was required
- Layout revamp on page for assigning multiple members to a series (check different widths)
- Dashboard layout fixes (papers were off center once they stacked into a column)
- Add app grey background and improve padding on AppBar
- Add expansion panel on CreatePost explaining "days from start" using Moment.
> Training Series page, dashboard polish and improvements

- client/src/components/Notifications/Notification.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TrainingSeriesAssigments.js
- client/src/components/TrainingSeries/TrainingSeriesAssignment.js
* Adjust moment formatter to display proper date regardless of US time zone.
> FIX: Time display bug

- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
* Adjust display text to be more clear.
* Remove old console log
> Text and email selection style

- client/package.json
- client/src/components/Notifications/Notification.js
- client/yarn.lock
Phone numbers on notifications dashboard are now formatted
> phone numbers formatted on notifications page

- client/src/components/AppBar/AppBar.js
- client/src/components/Callback/callback.js
- client/src/components/Dashboard/DashboardView.js
- client/src/components/Profile/ProfileView.js
- client/src/components/TeamMembers/TeamMembersView.js
- client/src/components/Tour/Tour.js
- client/src/components/TrainingSeries/TrainingSeriesSubView.js
- client/src/store/reducers/userReducer.js
The tutorial didn't quite make it into dev. You should now be able to see the tutorial and inside of profile there is now a button to re-activate the tutorial.
> Re-implemented tutorial into app

- client/src/components/TrainingSeries/TrainingSeriesPosts.js
* Add sort function to sort messages by days from start.
> Add sort for messages, sorts by daysFromStart

- client/src/components/LandingPage/LandingPageView.js
- client/src/components/LandingPage/Pricing.js
- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/SnackBarTeamMember.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/routes.js
Forgot to create a new branch for these.
- Landing page links to pricing page.
- Pricing page includes a basic chart
- When adding a phone number to a new team member the add member is disabled until a valid number is entered or none is added.
- When editing a team members phone number the save button is disabled unless a valid number is entered or none at all
> Pricing page & phone number regex

- client/src/components/Stripe/CheckoutForm.js
* Add color to actively selected subscription type while form is active.
* Adjust responsiveness of payment form to handle mobile width
> Pricing subscription button color when active

- client/src/components/LandingPage/Pricing.js
- client/src/components/Stripe/CheckoutForm.js
- client/src/components/authenticate/authenticate.js
Updated pricing page and pages that are restricted when logged out such as https://trainingbot-dev.netlify.com/home/
> Profile pricing & restricted pages

- client/src/components/TeamMembers/TeamMemberPageContainer/AddTeamMemberPage.js
- client/src/components/TeamMembers/TeamMemberPageContainer/TeamMemberPage.js
- client/src/components/TrainingSeries/TrainingSeriesPosts.js
- client/src/store/reducers/trainingSeriesReducer.js
- client/yarn.lock
Edit training series no longer shows the loader on save
add new member no longer requires an email.
> Edit training title and new member form updates

- client/src/components/LandingPage/Team.js
- Edited form to try to debug. Merging automatically to test.
> Change form attribute to netlify to test

- client/public/index.html
- client/src/components/LandingPage/Team.js
- Added static form to index.hteml
- Added hidden input to JSX form inside Team.js
(Based on article here: https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/)
> Hopeful bug fix for Netlify form

- client/public/index.html
- client/src/components/LandingPage/FormSuccess.js
- client/src/components/LandingPage/Team.js
- client/src/components/Tour/Tour.js
- client/src/routes.js
- Add success page to render upon submitting contact form
- Add link to team page on last frame of new user tour
> Form success page
